version: "3.8"

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        user: root
        restart: ${RESTART_POLICY}
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - db
        networks:
            - coneccion_v1

    db:
        image: postgres
        container_name: postgres
        user: root
        volumes:
            - 'db_volumen_v1:/var/lib/postgresql/data'
        ports:
            - "5432:5432"
        restart: ${RESTART_POLICY}
        environment:
            POSTGRES_DB: "traceability"
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "i39f6^O+`8QI"
            POSTGRES_HOST_AUTH_METHOD: 'md5'
        networks:
            - coneccion_v1

    app:
        container_name: Traceability
        user: root
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        working_dir: /var/www
        restart: ${RESTART_POLICY}
        command: bash -c "chown -R www-data:www-data storage bootstrap/cache && chmod -R 775 storage bootstrap/cache && php-fpm"
        networks:
            - coneccion_v1

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgAdmin
        user: root
        restart: ${RESTART_POLICY}
        ports:
            - "5050:80"
        depends_on:
            - db
            - app
        environment:
            PGADMIN_DEFAULT_EMAIL: "fc089609@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "i39f6^O+`8QI"
        networks:
            - coneccion_v1

networks:
    coneccion_v1:
        driver: bridge

volumes:
  db_volumen_v1:
