name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: SSH into server Pull Git
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.IP_PRODUCTION }}
        username: ${{ secrets.USER_PRODUCTION_PULL }}
        passphrase: ${{ secrets.PSS_PRODUCTION_PULL }}
        key: ${{ secrets.SSH_PRODUCTION_PULL }}
        port: 538
        script: |
          cd ${{ secrets.PATH_PRODUCTION }}
          git pull origin master
    - name: SSH into server Docker
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.IP_PRODUCTION }}
        username: ${{ secrets.USER_PRODUCTION_DOCKER }}
        passphrase: ${{ secrets.PSS_PRODUCTION_DOCKER }}
        key: ${{ secrets.SSH_PRODUCTION_DOCKER }}
        port: 538
        script: |
          cd ${{ secrets.PATH_PRODUCTION }}
          docker compose up --build -d
